# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  # namespace: 'lct-namespace'
  # imageName: 'kenik/lct'
  # deploymentName: 'lct-api'

stages:
- stage: Build 
  displayName: Build project
  jobs :
  - job: Build
    displayName: project build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: AzureKeyVault@2
        inputs:
          azureSubscription: 'Free(526e617c-4cc8-4299-a7ee-ef1c637e45a0)'
          KeyVaultName: 'lct-kvvv'
          SecretsFilter: '*'
          RunAsPreJob: true
- stage: Release
  displayName: Build image
  jobs:
  - job: Build2
    displayName: Image build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        containerRegistry: 'dockerHub'
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/LCT/Dockerfile'
        tags: |
          $(TAG)
          latest
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'lct-k8s'
        namespace: $(namespace)
        command: 'apply'
        arguments: '-f $(Build.SourcesDirectory)/deployment.yaml'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'lct-k8s'
        namespace: $(namespace)
        command: 'set'
        arguments: 'image deployment/$(deploymentName) $(deploymentName)=$(imageName) -n $(namespace)'
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'lct-k8s'
        namespace: $(namespace)
        command: 'rollout'
        arguments: 'restart deployment/$(deploymentName)'
