# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build 
  displayName: Build project
  jobs :
  - job: Build
    displayName: project build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '$(Build.SourcesDirectory)/LCT'
- stage: Release
  displayName: Build image
  jobs:
  - job: Build
    displayName: Image build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'kenik/lct'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/LCT/Dockerfile'
        tags: |
          $(TAG)
          latest
