apiVersion: apps/v1
kind: Deployment
metadata:
  name: lct-api
  namespace: lct-namespace
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: lct-api-deployment
  template:
    metadata:
      labels:
        app: lct-api-deployment
    spec:
      containers:
        - name: lct-api
          image: localhost:7000/lct:latest
          # image: kenik/lct
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 200
          resources:
            requests:
                memory: 200Mi
                cpu: 200m
            limits:
                memory: 300Mi
                cpu: 350m
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+:80w
          - name: Mongo__ConnectionString
            value: mongodb+srv://admin:pass@lct-cluster.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000
          - name: Mongo__DatabaseName
            value: Lct_Dev
          - name: ElasticConfiguration__Uri
            value: http://172.17.0.1:9200
          - name: Redis__ConnectionString
            value: 172.17.0.1:6379
          - name: Redis__Password
            value: "123456"