apiVersion: apps/v1
kind: Deployment
metadata:
  name: lct-api-deployment
spec:
  replicas: 5
  selector: 
    matchLabels:
      app: lct-api
  template:
    metadata:
      labels:
        app: lct-api
    spec:
      containers:
        - name: lct-api
          image: localhost:7000/lct:latest
          imagePullPolicy: Always
          resources:
            requests:
                memory: "200Mi"
                cpu: "200m"
            limits:
                memory: "300Mi"
                cpu: "350m"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: http://+:80w
          - name: Mongo__ConnectionString
            value: mongodb://172.17.0.1:27021
          - name: Mongo__DatabaseName
            value: Lct_Dev
          - name: fe__ConnectionString
            value: 172.17.0.1:3000
          - name: ElasticConfiguration__Uri
            value: http://172.17.0.1:9200
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app: lct-api
            topologyKey: kubernetes.io/hostname