version: "3.7"
services: 
    lct-db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - 1433:1433
        environment:
            SA_PASSWORD: "MyPassword001"
            ACCEPT_EULA: "Y"