version: "3.7"
services: 
    lct-db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - 1433:1433
        environment:
            SA_PASSWORD: "MyPassword001"
            ACCEPT_EULA: "Y"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - "9400:9200"
            - "9500:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.0
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
    eventstore.db:
        image: eventstore/eventstore:20.10.2-buster-slim
        environment:
          - EVENTSTORE_CLUSTER_SIZE=1
          - EVENTSTORE_RUN_PROJECTIONS=All
          - EVENTSTORE_START_STANDARD_PROJECTIONS=true
          - EVENTSTORE_EXT_TCP_PORT=1113
          - EVENTSTORE_HTTP_PORT=2113
          - EVENTSTORE_INSECURE=true
          - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
          - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
        ports:
          - "1113:1113"
          - "2113:2113"
volumes:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: bridge