version: "3.7"
services: 
    lct-db:
        image: "mcr.microsoft.com/mssql/server"
        ports:
        - 1433:1433
        environment:
            SA_PASSWORD: "MyPassword001"
            ACCEPT_EULA: "Y"
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
        container_name: elasticsearch
        environment:
            - discovery.type=single-node
        ports:
            - "9400:9200"
            - "9500:9300"
        volumes:
            - esdata:/usr/share/elasticsearch/data
        networks:
            - esnetwork
    kibana:
        image: docker.elastic.co/kibana/kibana:6.3.0
        ports:
            - "5601:5601"
        networks:
            - esnetwork
        depends_on:
            - elasticsearch
    mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - ~/apps/mongo:/data/db
        environment:
          - MONGO_INITDB_ROOT_USERNAME=citizix
          - MONGO_INITDB_ROOT_PASSWORD=S3cret

volumes:
    eventstore-volume-data:
    eventstore-volume-logs:
    esdata:
        driver: local
networks:
    esnetwork:
        driver: bridge