apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: lct-api-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: lct-api-deployment
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 30