apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lct-kvvv
  namespace: lct-namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "lct-kvvv"
    objects: |
      array:
        - |
          objectName: namespace
          objectType: secret
    tenantId: "0bafd6e3-1aac-4267-813f-5350bfe9ffb0"