apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: lct-kv
  namespace: lct-namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    keyvaultName: "lct-kv"
    objects: |
      array:
        - |
          objectName: namespace
          objectType: secret
    tenantId: "..."